name: Get Release Message
on: workflow_dispatch
jobs:
  build:
    name: Get Fonts From Icomoon
    runs-on: ubuntu-18.04
    steps:
      - name: Run the get_release_message.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python ./.github/scripts/get_release_message.py $GITHUB_TOKEN